### PR TITLE
fixed naming

### LINKED ISSUE #636: Download-spectrum name
Following the neat #619 implementation of Download (👏  ) 

File name  : 
- should at least have the molecule name  
- should have "cm-1"  (i.e. `1900-2300cm-1.spec`)
- can you add temperature (followed by `K` ) , pressure (followed by `atm` ) databank name ?   

image

### PR DESCRIPTION
**Pull request by arunavabasu-03**
Fixes #636

### CODE REVIEW

File: frontend/src/components/CalcSpectrum.tsx [hunk 1]
```diff
@@ -201,7 +201,7 @@ export const CalcSpectrum: React.FC = () => {
         link.href = url;
         link.setAttribute(
           "download",
-          `${data.mode}_${data.min_wavenumber_range}_${data.max_wavenumber_range}.spec`
+          `${data.database}_${data.species[0].molecule}_${data.min_wavenumber_range}_${data.max_wavenumber_range}cm-1_${data.tgas}K_${data.pressure}atm.spec`
```
Comment (suzil) [inline frontend/src/components/CalcSpectrum.tsx:204]: Should we do something like this in case the user has selected multiple molecules?
Screen Shot 2022-08-22 at 10 38 11 AM

**Comment by suzil** [comment]
Fine for me, but I'll let @erwanp review the file name formatting for this PR.

**Review by suzil — APPROVED** [review]

File: frontend/src/components/CalcSpectrum.tsx [hunk 2]
```diff
@@ -201,7 +204,7 @@ export const CalcSpectrum: React.FC = () => {
         link.href = url;
         link.setAttribute(
           "download",
-          `${data.mode}_${data.min_wavenumber_range}_${data.max_wavenumber_range}.spec`
+          `${data.database}_${molecules}_${data.min_wavenumber_range}_${data.max_wavenumber_range}cm-1_${data.tgas}K_${data.pressure}atm.spec`
```
Comment (erwanp) [inline frontend/src/components/CalcSpectrum.tsx:207]: What happens if there are nonequilibrium conditions ? 
Then you'll need Tvib, Trot

**Review by erwanp — CHANGES_REQUESTED** [review]

File: frontend/src/components/CalcSpectrum.tsx (hunk 2 above)
Comment (erwanp) [reply frontend/src/components/CalcSpectrum.tsx:207]: also, what happens if there are multiple molecules ? It may because complicated to look over all molecules, just write "gas_mixture" if N molecules > 1 ?

Comment (arunavabasu-03) [reply frontend/src/components/CalcSpectrum.tsx:207]: I think @erwanp it is great to put this way because that is going to show `undefined`

Comment (erwanp) [reply frontend/src/components/CalcSpectrum.tsx:207]: Your implementation does not work if downloading a Spectrum of multiple molecules. I tried it

**Review by erwanp — APPROVED** [review]
good!
